# Generated by Django 5.0.4 on 2024-06-18 12:09

import django.db.models.deletion
import isbn_field.fields
import isbn_field.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('social_media_twitter', models.URLField(blank=True, null=True)),
                ('social_media_facebook', models.URLField(blank=True, null=True)),
                ('social_media_linkedin', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mailing_address', models.TextField(blank=True)),
                ('biography', models.TextField(blank=True)),
                ('awards_recognitions', models.TextField(blank=True)),
                ('is_deceased', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='author_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Edition',
                'verbose_name_plural': 'Editions',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('founding_date', models.DateField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='publisher_logos')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed'), ('other', 'Other')], default='active', max_length=10)),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_date', models.DateField()),
                ('volume', models.IntegerField()),
                ('isbn', isbn_field.fields.ISBNField(clean_isbn=False, max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('description', models.TextField(blank=True)),
                ('book_cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers')),
                ('series_cover_image', models.ImageField(blank=True, null=True, upload_to='series_covers')),
                ('authors', models.ManyToManyField(related_name='books', to='app.author')),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app.edition')),
                ('genres', models.ManyToManyField(related_name='books', to='app.genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app.language')),
                ('collaborating_publishers', models.ManyToManyField(blank=True, related_name='collaborating_books', to='app.publisher')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiobook_file', models.FileField(upload_to='audiobooks/')),
                ('duration', models.DurationField()),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audiobook', to='app.book')),
            ],
            options={
                'verbose_name': 'Audiobook',
                'verbose_name_plural': 'Audiobooks',
            },
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebook_file', models.FileField(upload_to='ebooks/')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ebook', to='app.book')),
            ],
            options={
                'verbose_name': 'Ebook',
                'verbose_name_plural': 'Ebooks',
            },
        ),
        migrations.CreateModel(
            name='PenName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_name', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pen_names', to='app.author')),
            ],
            options={
                'verbose_name': 'Pen Name',
                'verbose_name_plural': 'Pen Names',
            },
        ),
        migrations.CreateModel(
            name='Imprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('founding_date', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='imprint_logos')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imprints', to='app.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='current_publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_authors', to='app.publisher'),
        ),
        migrations.AddField(
            model_name='author',
            name='past_publishers',
            field=models.ManyToManyField(blank=True, related_name='past_authors', to='app.publisher'),
        ),
    ]
