# Generated by Django 5.0.4 on 2024-06-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_author_awards_recognitions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='past_publishers',
            field=models.ManyToManyField(blank=True, related_name='past_authors', to='app.publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='collaborating_publishers',
            field=models.ManyToManyField(blank=True, related_name='collaborating_books', to='app.publisher'),
        ),
    ]
